title: "Yaser Elbably — Data Analyst"
description: "محلل بيانات مستقل بخبرة هندسية يقدم حلول تحليلية متكاملة"
url: "" # أضف هنا نطاقك لاحقًا إن وجد
baseurl: "" # لا تضع أي قيمة إذا كنت تستخدم GitHub Pages من الفرع الرئيسي

author:
  name: "م. ياسر"
  email: "eng.yaserelbably@gmail.com"

social:
  linkedin: "https://www.linkedin.com/in/yaserosamaelbably/"
  github: "https://github.com/YaserOsamaElbably"

# إعدادات GitHub Pages
markdown: kramdown
theme: jekyll-theme-minimal
