title: "Yaser Elbably — Data Analyst"
description: "محلل بيانات مستقل بخبرة هندسية يقدم حلول تحليلية متكاملة"
url: "https://yaserosamaelbably.github.io"
baseurl: "/agency-jekyll-theme"

author:
  name: "م. ياسر"
  email: "eng.yaserelbably@gmail.com"

social:
  linkedin: "https://www.linkedin.com/in/yaserosamaelbably/"
  github: "https://github.com/YaserOsamaElbably"

markdown: kramdown
theme: null
